apache/solr-sandbox

crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/Consumer.java

This change corrects the `if` statements in the consumer start, so that it
actually checks the config being passed.
Previously it just checked the `bootstrapServers` three times.

Fix startup checks

---

crossdc-commons/src/main/java/org/apache/solr/crossdc/common/KafkaCrossDcConf.java

This change adds a human readable `toString` function to `KafkaCrossDcConf`.
Instead of seeing messages like this:
```
Configurations org.apache.solr.crossdc.common.KafkaCrossDcConf@7953c5d9
```
We now get:
```
Configurations KafkaCrossDcConf{topicName='topic1',
enableDataEncryption='false', bootstrapServers='127.0.0.1:57559',
slowSubmitThresholdInMillis='0', numOfRetries='5', solrZkConnectString='null'}
```

KafkaCrossDcConf: Add a human readable toString

---

CROSSDC.md
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/CrossDcConf.java
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/KafkaCrossDcConf.java
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/KafkaMirroringSink.java
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/MirroredSolrRequestSerializer.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/Consumer.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumer.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/KafkaRequestMirroringHandler.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateProcessor.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateRequestProcessorFactory.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/DeleteByQueryToIdTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/RetryQueueIntegrationTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaIntegrationTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaReindexTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/ZkConfigIntegrationTest.java

Adds a basic test focused on reindexing, covers a few more test cases: more replicas and shards, different shard count on primary and secondary dc, allows consumer group to be configured, allows crossdc zk prop file location to be configured.

Reindex Test, cover a few more test cases, additional config options.

---

crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateProcessor.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateRequestProcessorFactory.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaIntegrationTest.java
crossdc-producer/src/test/resources/configs/cloud-minimal/conf/solrconfig.xml

Prior to this commit, the MirroringUpdateProcessor had no check to ensure that docs weren't running afoul of the batch size limit set at the Kafka level.
This commit changes this to ensure that docs exceeding this limit are not mirrored.  These offending docs may still be indexed, based on the value of the URP's "indexUnmirrorableDocs" config property (which defaults to 'false' if not set).

Check docSize against max before mirroring

---

crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateProcessor.java

The logging call was missing a needed template argument for the docId.

Fix log message printed when mirroring skipped for large doc

---

crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateProcessor.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateRequestProcessorFactory.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaIntegrationTest.java

Prior to this commit, MirroringUpdateProcessor checked that individual documents didn't exceed the mirroring batch-size limit on their own, but no check existed to ensure that the entire list of docs doesn't exceed the limit.
This commit adds that check (in MirroringUpdateProcessor.finish()).  If the configured max batch-size is exceeded, MUP will log out an error (which includes the IDs of all documents in the batch).

Check batch-size against "max" before mirroring

---

crossdc-commons/src/main/java/org/apache/solr/crossdc/common/KafkaCrossDcConf.java
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/SensitivePropRedactionUtils.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/Consumer.java

Prior to this commit, certain log messages during Producer/Consumer startup contained potentially sensitive information, such as SSL passwords, etc.
This commit amends the string-ification of KafkaCrossDcConf and other Map/Properties types to "redact" properties whose key/name contains a block-list of values.  This list currently consists of "password" and "credentials": any property name containing these substrings (ignoring case) will be redacted before logging.

Redact properties before string-ifying or logging

---

ENCRYPTION.md
encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectoryFactory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUtil.java
encryption/src/main/java/org/apache/solr/encryption/KeySupplier.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionDirectoryTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionHeavyLoadTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionMergePolicyFactoryTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/TestingEncryptionRequestHandler.java
encryption/src/test/java/org/apache/solr/encryption/TestingKeySupplier.java
encryption/src/test/resources/configs/collection1/solrconfig.xml

Additional parameters can be provided to the EncryptionRequestHandler in the SolrQueryRequest. The handler can be extended to send the relevant parameters to the KeySupplier when retrieving the key cookie (generic key-value pairs).

Encryption KeySupplier supports params to get the key cookie.

---

ENCRYPTION.md
encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionMergePolicy.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUtil.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionHeavyLoadTest.java

Now EncryptionHeavyLoadTest passes the 20min run bar.
This means we can enable EncryptionMergePolicy which re-encrypts each index segment individually. This is way faster than an optimized merge into a single segment as previously:
- No time spent to merge all segments into one.
- We leverage Lucene concurrent merge: segments are re-encrypted by parallel threads from the mergers pool.

Fix EncryptionMergePolicy to reencrypt each segment separately.

---

crossdc-consumer/src/main/java/org/apache/solr/crossdc/messageprocessor/SolrMessageProcessor.java

As-is, much of the producer logging is unhelpful without being able to discern which collections are receiving traffic.

Add 'collection' MDC to more consumer logs

---

encryption/build.gradle
encryption/src/main/java/org/apache/solr/encryption/crypto/CharStreamEncrypter.java
encryption/src/main/java/org/apache/solr/encryption/crypto/CipherAesCtrEncrypter.java
encryption/src/main/java/org/apache/solr/encryption/crypto/DecryptingInputStream.java
encryption/src/main/java/org/apache/solr/encryption/crypto/EncryptingOutputStream.java
encryption/src/test/java/org/apache/solr/encryption/crypto/AesCtrEncrypterTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/CharStreamEncrypterTest.java

CharStreamEncrypter is a nearly standalone tool to encrypt a character stream to a base 64 encoding compatible with JSON. The whole encryption and base 64 encoding process is streamed, with no large buffers allocated. The encryption transformation is AES/CTR/NoPadding. A secure random IV is generated for each encryption and appended as the first appended chars.
It depends on commons-codec Base64OutputStream/Base64InputStream, and commons-io ReaderInputStream/WriterOutputStream/AppendableWriter.

Add CharStreamEncrypter.

---

crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateRequestProcessorFactory.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/CrossDCProducerSolrStandaloneTest.java
crossdc-producer/src/test/resources/configs/cloud-minimal/conf/solrconfig-producerdisabled.xml

XDC really only makes sense in a SolrCloud context.  But all the same, it's nice to handle MirroringUpdateRequestProcessorFactory more gracefully if someone does accidentally configure their standalone core to use the XDC producer URP.
This commit tweaks MirroringUpdateRequestProcessorFactory's initialization so that in standalone mode it emits a warning about the misconfiguration if disabled, and fails core init/load entirely if the Mirroring URP is 'enabled=true'.

Ignore producer URP (if disabled) in standalone mode

---

crossdc-consumer/src/test/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumerTest.java

Some tests in `KafkaCrossDcConsumerTest` were failing because they were using the real `KafkaConsumer` instance that is looking for a Kafka server. Unfortunately there was no instance on the localhost so it could not establish the connection and pass the tests.

KafkaCrossDcConsumerTest fix

---

crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumer.java
crossdc-consumer/src/test/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumerTest.java

When the first request is an ADMIN request and only then an UPDATE request is sent at this point the updateReqBatch is still null and sendBatch causes NPE.

Fix KafkaCrossDcConsumer NPE, add unit test.

---

crossdc-commons/build.gradle
crossdc-consumer/build.gradle
crossdc-producer/build.gradle
crossdc-producer/src/main/java/org/apache/solr/handler/admin/MirroringConfigSetsHandler.java
crossdc-producer/src/test/java/org/apache/solr/handler/admin/MirroringConfigSetsHandlerTest.java

The project uses version 2.8.1. I propose to upgrade it to a recent version of 3.x (3.5.1) to benefit from many improvements, especially important for the cross-dc mirroring use case (Kafka Connect, MirrorMaker 2, stronger delivery guarantees, etc).

Upgrade Kafka to 3.5.1

---

crossdc-producer/build.gradle
crossdc-producer/src/test/java/org/apache/solr/crossdc/RetryQueueIntegrationTest.java

This started failing after recent changes. It turns out that the time between Solr shutdown and restart was sometimes long enough to exhaust the default maxAttempts and the messages were sent to DLQ. The irony is that the test incorrectly expected infinite attempts, and it started failing after PR82 which fixed the maxAttempts functionality.

RetryQueueIntegrationTest failures

---

CROSSDC.md
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/CrossDcConf.java
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/KafkaCrossDcConf.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/Consumer.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumer.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateProcessor.java
crossdc-producer/src/main/java/org/apache/solr/update/processor/MirroringUpdateRequestProcessorFactory.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/DeleteByQueryToIdTest.java
crossdc-producer/src/test/java/org/apache/solr/update/processor/MirroringUpdateProcessorTest.java
crossdc-producer/src/test/resources/configs/cloud-minimal-no-dbq/conf/schema.xml
crossdc-producer/src/test/resources/configs/cloud-minimal-no-dbq/conf/solrconfig-producerdisabled.xml
crossdc-producer/src/test/resources/configs/cloud-minimal-no-dbq/conf/solrconfig.xml

This PR adds a boolean config option `expandDbq` (defaults to true) that allows to control whether Delete-By-Query should be expanded on the source-side into a series of Delete-By-Ids. There are tradeoffs in either case so it makes sense to expose this as a configurable option.

Add support for optional DBQ expansion.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectoryFactory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionTransactionLog.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUpdateLog.java
encryption/src/main/java/org/apache/solr/encryption/KeySupplier.java
encryption/src/main/java/org/apache/solr/encryption/crypto/CharStreamEncrypter.java
encryption/src/main/java/org/apache/solr/encryption/crypto/EncryptingIndexOutput.java
encryption/src/main/java/org/apache/solr/update/TransactionLog.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionHeavyLoadTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionTestUtil.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionUpdateLogTest.java
encryption/src/test/java/org/apache/solr/encryption/TestingKeySupplier.java
encryption/src/test/java/org/apache/solr/encryption/crypto/AesCtrEncrypterTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/CharStreamEncrypterTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/CryptoTestUtil.java
encryption/src/test/java/org/apache/solr/encryption/crypto/DecryptingChannelInputStreamTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/DecryptingIndexInputTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/EncryptingIndexOutputTest.java
encryption/src/test/java/org/apache/solr/encryption/crypto/EncryptingOutputStreamTest.java
encryption/src/test/resources/configs/collection1/solrconfig.xml

A better test showed some interactions between EncryptionRequestHandler and EncryptionUpdateLog missed.
This PR adds some methods in EncryptionUpdateLog and makes EncryptionRequestHandler call them.
Also refactor some parts of tests classes to share common code.

Encrypt handler calls EncryptionUpdateLog to reencrypt logs. Rewrite the test.

---

CROSSDC.md
crossdc-commons/src/main/java/org/apache/solr/crossdc/common/IQueueHandler.java
crossdc-consumer/build.gradle
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/Consumer.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumer.java
crossdc-consumer/src/main/java/org/apache/solr/crossdc/messageprocessor/SolrMessageProcessor.java
crossdc-consumer/src/test/java/org/apache/solr/crossdc/consumer/KafkaCrossDcConsumerTest.java
crossdc-consumer/src/test/java/org/apache/solr/crossdc/messageprocessor/SolrMessageProcessorTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/DeleteByQueryToIdTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/RetryQueueIntegrationTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaIntegrationTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaMultiCollectionIntegrationTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/SolrAndKafkaReindexTest.java
crossdc-producer/src/test/java/org/apache/solr/crossdc/ZkConfigIntegrationTest.java

This PR adds a Jetty-based server + servlet to expose the collected consumer metrics.
I added two endpoints:
* `/threads` to view a thread dump
* `/metrics` to view the collected metrics
I attached [an example output ](https://github.com/apache/solr-sandbox/files/13451534/metrics.json)  from the /metrics endpoint.

Add endpoint to expose consumer metrics.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionTransactionLog.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUpdateLog.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUtil.java

Remove the optimization as it does not work in the case of an initially empty directory that is later filled with the index files. Also, it does not bring much performance or IO improvement.

Remove EncryptionDirectory.shouldCheckEncryptionWhenReading optimization.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionMergePolicy.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUpdateLog.java
encryption/src/main/java/org/apache/solr/encryption/EncryptionUtil.java

The "encryption" is not useful to search logs as one can search with the package name "encrypt". Remove this prefix for simpler code.

Remove encryption log prefix.

---

encryption/build.gradle
encryption/src/main/java/org/apache/solr/encryption/EncryptionBackupRepository.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionBackupRepositoryTest.java
encryption/src/test/resources/configs/collection1/solrconfig.xml

A new EncryptionBackupRepository is required to backup correctly files encrypted with the EncryptionDirectory, otherwise index files are decrypted before the backup copy. EncryptionBackupRepository ensures the encrypted files are copied encrypted, but still verifies their checksum before the copy. It also ensures the files are copied encrypted when restored (not double encrypted).
EncryptionBackupRepository extends DelegatingBackupRepository, so it requires solr 9.6.0.

EncryptionBackupRepository to back up encrypted files.

---

ENCRYPTION.md

EncryptionBackupRepository was added in a previous commit, but we missed its description in ENCRYPTION.md.

Update ENCRYPTION.md to describe EncryptionBackupRepository.

---

ENCRYPTION.md
encryption/build.gradle
encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectoryFactory.java
encryption/src/main/java/org/apache/solr/encryption/crypto/AesCtrUtil.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsClient.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsEncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsKeyCache.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsKeySupplier.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsMetrics.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionBackupRepositoryTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionHeavyLoadTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionTestUtil.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionUpdateHandlerSplitTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionUpdateLogTest.java
encryption/src/test/java/org/apache/solr/encryption/TestingKeySupplier.java
encryption/src/test/java/org/apache/solr/encryption/kms/KmsEncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/kms/KmsKeySupplierTest.java
encryption/src/test/java/org/apache/solr/encryption/kms/SpyingKmsMetrics.java
encryption/src/test/java/org/apache/solr/encryption/kms/TestingKmsClient.java
encryption/src/test/java/org/apache/solr/encryption/matcher/EventuallyMatcher.java
encryption/src/test/resources/configs/kms/schema.xml
encryption/src/test/resources/configs/kms/solrconfig.xml

Added a new section in ENCRYPTION.md, here is an extract for the description:
If you have a Key Management System to manage the encryption keys lifecycle, then you can use the `org.apache.solr.encryption.kms.KmsKeySupplier`. In this case, it requires that the Solr client sends some key blob
to the `EncryptionRequestHandler` in addition to the key id. The key blob contains an encrypted form of the key secret
and enough data for your KMS to decrypt it and provide the clear-text key secret. The key blob is stored in the
metadata of each index file. And when needed, the `KmsKeySupplier` calls your KMS with your `KmsClient` to decrypt the
key blob and store the key secret in an in-memory key cache with automatic wiping of the cache entries after some short
duration.
`KmsKeySupplier` requires …

Add KmsKeySupplier that calls a KmsClient to decrypt encryption keys.

---

encryption/build.gradle
encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java
encryption/src/main/java/org/apache/solr/encryption/crypto/CharStreamEncrypter.java
encryption/src/main/java/org/apache/solr/encryption/kms/KmsEncryptionRequestHandler.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionDirectoryTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionHeavyLoadTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionTestUtil.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionUpdateLogTest.java
encryption/src/test/java/org/apache/solr/encryption/TestingEncryptionRequestHandler.java
encryption/src/test/java/org/apache/solr/encryption/kms/KmsEncryptionRequestHandlerTest.java

The client can call EncryptionRequestHandler and provide the additional parameter "distrib" = "true". In this case, this handler will distribute the encryption request to all the leader replicas of all the shards of the collection, ensuring they all encrypt their index shard. The response "encryptionState" will be "complete" only when all the shards return "complete". So the caller may repeatedly send the same encryption request with "distrib" = "true" to know when the whole collection encryption is complete. In addition, the caller can set the "timeAllowed" parameter to define a timeout for the request distribution, in milliseconds. This timeout is for the distribution itself, not the encryption process.

EncryptionRequestHandler supports encryption requests distribution.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionRequestHandlerTest.java
encryption/src/test/java/org/apache/solr/encryption/EncryptionTestUtil.java

The problem is described in the corresponding [issue](https://github.com/apache/solr-sandbox/issues/109).
It happens when documents are inserted but without commit, and the IndexWriter is closed, which triggers an auto-commit from DirectUpdateHandler2.closeWriter. Unfortunately this auto-commit does not really call the DirectUpdateHandler2.commit code but rather copies it, and we miss a call to DirectUpdateHandler2.shouldCommit to manage the encryption commit metadata.
Actually this requires to change DirectUpdateHandler2.closeWriter in the Solr project.
This PR shows the small required change (see comment in the DirectUpdateHandler2 copy), and verifies the fix with a test.
But I don't think I'll merge this PR. I'll rather change upstream and wait for the next release to upgrade here.

Transfer encryption metadata in the commit when DirectUpdateHandler2.closeWriter is called.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionDirectory.java
encryption/src/main/java/org/apache/solr/encryption/crypto/AesCtrEncrypter.java
encryption/src/main/java/org/apache/solr/encryption/crypto/AesCtrUtil.java
encryption/src/main/java/org/apache/solr/encryption/crypto/DecryptingIndexInput.java
encryption/src/main/java/org/apache/solr/encryption/crypto/EncryptingIndexOutput.java

Makes DecryptingIndexInput extend FilterIndexInput, and EncryptingIndexOutput extend FilterIndexOutput, in case one need to unwrap the Filter input/output.
Also adds more doc about the choice of the CTR-mode, and the nonce-misuse resistance when building the random IV.

Encryption IndexInput and IndexOutput can be unwrapped. More doc about IV construction.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java

Single line added: call Thread.interrupt() in try-catch InterruptedException.

Add missing Thread.interrupt() call in EncryptionRequestHandler.

---

encryption/src/main/java/org/apache/solr/encryption/EncryptionRequestHandler.java

No functional change, only refactoring to split the two large methods handleRequestBody() and distributeRequest(). It reduces the cyclomatic complexity and I hope it clarifies the code despite adding 100 lines.
Unit tests pass after refactoring.

Refactor EncryptionRequestHandler to split large methods.
